import { QRCodeItem, QRCustomization, ScanLog, StoredFile, UserProfile, QRTemplate, AccentColor, ThemeMode } from '@/types';

export const DEFAULT_CUSTOMIZATION: QRCustomization = {
  fgColor: '#4f46e5',
  bgColor: '#ffffff',
  gradientEnabled: true,
  gradientColor: '#7c3aed',
  gradientType: 'linear',
  gradientDirection: 'to-br',
  pattern: 'rounded',
  eyeStyle: 'rounded',
  eyeColor: '#4338ca',
  logoUrl: null,
  logoSize: 20,
  frame: 'scanner',
  frameText: 'SCAN TO VIEW',
  frameColor: '#4f46e5',
  ecl: 'Q',
  margin: 2,
  size: 300,
};

export const DEMO_USER_PROFILE: UserProfile = {
  name: 'Alex Rivera',
  email: 'alex.rivera@qrverse.dev',
  title: 'Lead Software Architect & Product Strategist',
  bio: 'Passionate about building modern web architecture, cloud-native services, and interactive digital experiences. 8+ years experience leading engineering teams.',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=500&q=80',
  skills: ['TypeScript', 'Next.js', 'React', 'Node.js', 'PostgreSQL', 'System Architecture', 'UI/UX Design'],
  education: [
    { school: 'Stanford University', degree: 'B.S. Computer Science', year: '2014 - 2018' },
    { school: 'MIT Executive Education', degree: 'Cloud Infrastructure Certification', year: '2021' },
  ],
  experience: [
    {
      company: 'Apex Tech Solutions',
      role: 'Principal Engineer',
      period: '2021 - Present',
      desc: 'Architected enterprise micro-frontend framework serving 4M+ daily active users.',
    },
    {
      company: 'Vanguard Digital',
      role: 'Senior Fullstack Engineer',
      period: '2018 - 2021',
      desc: 'Developed real-time streaming APIs and cloud data processing pipelines.',
    },
  ],
  projects: [
    { title: 'QRVerse Platform', link: 'https://qrverse.app', desc: 'Universal Dynamic QR experience platform with real-time analytics.' },
    { title: 'FlowGrid UI Engine', link: 'https://github.com/alexrivera/flowgrid', desc: 'High performance web component library.' },
  ],
  socials: [
    { platform: 'GitHub', url: 'https://github.com' },
    { platform: 'LinkedIn', url: 'https://linkedin.com' },
    { platform: 'Twitter', url: 'https://x.com' },
  ],
  phone: '+1 (555) 382-9102',
};

export const INITIAL_QR_CODES: QRCodeItem[] = [
  {
    id: 'qr-1',
    name: 'Executive Resume & Portfolio',
    slug: 'alex-resume',
    type: 'resume',
    mode: 'dynamic',
    status: 'active',
    accessControl: 'public',
    scansCount: 428,
    createdAt: '2026-08-15T10:00:00Z',
    updatedAt: '2026-09-01T14:30:00Z',
    customization: {
      ...DEFAULT_CUSTOMIZATION,
      fgColor: '#2563eb',
      gradientColor: '#3b82f6',
      frameText: 'SCAN FOR RESUME',
    },
    content: {
      profile: DEMO_USER_PROFILE,
      resumeUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    },
  },
  {
    id: 'qr-2',
    name: 'La Piazza Bistro Menu',
    slug: 'la-piazza-menu',
    type: 'menu',
    mode: 'dynamic',
    status: 'active',
    accessControl: 'public',
    scansCount: 1240,
    createdAt: '2026-08-01T09:15:00Z',
    updatedAt: '2026-09-05T18:00:00Z',
    customization: {
      ...DEFAULT_CUSTOMIZATION,
      fgColor: '#d97706',
      gradientColor: '#f59e0b',
      pattern: 'classy',
      eyeStyle: 'leaf',
      frameText: 'SCAN FOR MENU',
    },
    content: {
      restaurantName: 'La Piazza Bistro',
      tagline: 'Authentic Italian Dining & Fine Wine',
      address: '742 Evergreen Terrace, San Francisco, CA',
      phone: '+1 (415) 890-1234',
      categories: [
        {
          name: 'Antipasti',
          items: [
            { title: 'Bruschetta al Pomodoro', price: '$14', desc: 'Grilled sourdough, vine tomatoes, fresh basil, extra virgin olive oil' },
            { title: 'Carpaccio di Manzo', price: '$19', desc: 'Thinly sliced beef tenderloin, wild arugula, shaved Parmigiano' }
          ]
        },
        {
          name: 'Primi Piatti',
          items: [
            { title: 'Truffle Tagliolini', price: '$28', desc: 'Handmade egg pasta, black summer truffle, Parmigiano butter sauce' },
            { title: 'Rigatoni alla Carbonara', price: '$24', desc: 'Guanciale, egg yolk, Pecorino Romano, cracked black pepper' }
          ]
        }
      ]
    },
  },
  {
    id: 'qr-3',
    name: 'San Francisco Sunset Gallery',
    slug: 'sf-sunset-image',
    type: 'image',
    mode: 'dynamic',
    status: 'active',
    accessControl: 'public',
    scansCount: 312,
    createdAt: '2026-09-01T12:00:00Z',
    updatedAt: '2026-09-01T12:00:00Z',
    customization: {
      ...DEFAULT_CUSTOMIZATION,
      fgColor: '#f43f5e',
      gradientColor: '#fb7185',
      frameText: 'SCAN FOR IMAGE',
    },
    content: {
      title: 'Golden Gate Golden Hour',
      caption: 'Captured during peak autumn sunset over the Pacific ocean.',
      imageUrl: 'https://images.unsplash.com/photo-1506146332389-18140dc7b2fb?auto=format&fit=crop&w=1200&q=80',
      author: 'Alex Rivera Photography',
    },
  },
  {
    id: 'qr-4',
    name: 'Acoustic Ambient Soundtrack',
    slug: 'acoustic-track',
    type: 'audio',
    mode: 'dynamic',
    status: 'active',
    accessControl: 'public',
    scansCount: 520,
    createdAt: '2026-08-28T14:20:00Z',
    updatedAt: '2026-08-28T14:20:00Z',
    customization: {
      ...DEFAULT_CUSTOMIZATION,
      fgColor: '#06b6d4',
      gradientColor: '#38bdf8',
      pattern: 'dots',
      eyeStyle: 'dot',
      frameText: 'SCAN FOR AUDIO',
    },
    content: {
      title: 'Midnight Solitude (Acoustic Mix)',
      artist: 'Solaris Wave',
      album: 'Reflections Vol. 1',
      coverArtUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=600&q=80',
      audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    },
  },
  {
    id: 'qr-5',
    name: 'Product Keynote Reel',
    slug: 'product-reel-video',
    type: 'video',
    mode: 'dynamic',
    status: 'active',
    accessControl: 'public',
    scansCount: 740,
    createdAt: '2026-08-30T10:15:00Z',
    updatedAt: '2026-08-30T10:15:00Z',
    customization: {
      ...DEFAULT_CUSTOMIZATION,
      fgColor: '#8b5cf6',
      gradientColor: '#a855f7',
      frameText: 'SCAN FOR VIDEO',
    },
    content: {
      title: 'QRVerse 2.0 Keynote Release',
      description: 'Watch the full product announcement and feature deep-dive.',
      posterUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
      videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    },
  },
  {
    id: 'qr-6',
    name: 'Interactive Custom VIP Card',
    slug: 'custom-vip-pass',
    type: 'custom',
    mode: 'dynamic',
    status: 'active',
    accessControl: 'public',
    scansCount: 290,
    createdAt: '2026-09-02T16:00:00Z',
    updatedAt: '2026-09-02T16:00:00Z',
    customization: {
      ...DEFAULT_CUSTOMIZATION,
      fgColor: '#10b981',
      gradientColor: '#34d399',
      pattern: 'extra-rounded',
      frameText: 'SCAN VIP PASS',
    },
    content: {
      headline: 'VIP Founder Access Pass',
      badgeText: 'TIER 1 ACCESS',
      bodyText: 'Welcome to the exclusive QRVerse Founder Circle. Enjoy unlimited cloud file hosting and priority edge delivery.',
      ctaText: 'Claim Founder Benefit',
      ctaUrl: 'https://qrverse.app',
      themeBg: '#09090b',
      accentColor: '#10b981',
    },
  },
  {
    id: 'qr-7',
    name: 'Executive Contact vCard',
    slug: 'vcard-alex',
    type: 'contact',
    mode: 'static',
    status: 'active',
    accessControl: 'public',
    scansCount: 340,
    createdAt: '2026-08-18T14:00:00Z',
    updatedAt: '2026-08-18T14:00:00Z',
    customization: {
      ...DEFAULT_CUSTOMIZATION,
      fgColor: '#4f46e5',
      gradientColor: '#6366f1',
      frameText: 'SCAN TO SAVE CONTACT',
    },
    content: {
      name: 'Alex Rivera',
      organization: 'QRVerse Inc.',
      title: 'Lead Architect',
      phone: '+1 (555) 382-9102',
      email: 'alex.rivera@qrverse.dev',
      website: 'https://qrverse.app',
      address: 'San Francisco, CA',
    },
  }
];

export const INITIAL_FILES: StoredFile[] = [
  {
    id: 'file-1',
    name: 'QRVerse_Architecture_v2.4.pdf',
    type: 'application/pdf',
    size: 5033164,
    storageUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    downloads: 164,
    createdAt: '2026-09-03T15:45:00Z',
  },
  {
    id: 'file-2',
    name: 'Alex_Rivera_Executive_Resume.pdf',
    type: 'application/pdf',
    size: 1887436,
    storageUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    downloads: 428,
    createdAt: '2026-08-15T10:00:00Z',
  }
];

export const INITIAL_SCANS: ScanLog[] = [
  { id: 'scan-1', qrCodeId: 'qr-1', timestamp: '2026-09-08T14:10:00Z', device: 'Mobile', browser: 'Mobile Safari', os: 'iOS 18', location: 'San Francisco, US', referrer: 'Direct Scan' },
  { id: 'scan-2', qrCodeId: 'qr-2', timestamp: '2026-09-08T12:30:00Z', device: 'Mobile', browser: 'Mobile Safari', os: 'iOS 18', location: 'San Francisco, US', referrer: 'Direct Scan' },
  { id: 'scan-3', qrCodeId: 'qr-3', timestamp: '2026-09-08T11:15:00Z', device: 'Mobile', browser: 'Chrome Mobile', os: 'Android 15', location: 'San Jose, US', referrer: 'Direct Scan' },
  { id: 'scan-4', qrCodeId: 'qr-4', timestamp: '2026-09-08T10:05:00Z', device: 'Desktop', browser: 'Chrome 128', os: 'macOS 15', location: 'London, UK', referrer: 'Google Search' },
];

export const QR_TEMPLATES: QRTemplate[] = [
  {
    id: 'tpl-1',
    name: 'SaaS Executive',
    category: 'Corporate',
    description: 'Sleek dark violet theme with scanner badge frame for modern tech profiles and apps.',
    previewColor: '#4f46e5',
    customization: {
      ...DEFAULT_CUSTOMIZATION,
      fgColor: '#4f46e5',
      bgColor: '#ffffff',
      gradientEnabled: true,
      gradientColor: '#7c3aed',
      pattern: 'rounded',
      eyeStyle: 'rounded',
      eyeColor: '#4338ca',
      frame: 'scanner',
      frameText: 'SCAN TO CONNECT',
    },
  },
  {
    id: 'tpl-2',
    name: 'Gourmet Bistro',
    category: 'Restaurant',
    description: 'Warm amber tones with elegant classy pattern for digital menus and dining.',
    previewColor: '#d97706',
    customization: {
      ...DEFAULT_CUSTOMIZATION,
      fgColor: '#d97706',
      bgColor: '#fffbeb',
      gradientEnabled: true,
      gradientColor: '#b45309',
      pattern: 'classy',
      eyeStyle: 'leaf',
      eyeColor: '#92400e',
      frame: 'scanner',
      frameText: 'SCAN FOR MENU',
    },
  },
  {
    id: 'tpl-3',
    name: 'Minimal Mono',
    category: 'Minimal',
    description: 'Clean monochrome layout with high contrast for ultra-scannable prints.',
    previewColor: '#18181b',
    customization: {
      ...DEFAULT_CUSTOMIZATION,
      fgColor: '#09090b',
      bgColor: '#ffffff',
      gradientEnabled: false,
      gradientColor: '#09090b',
      pattern: 'square',
      eyeStyle: 'square',
      eyeColor: '#09090b',
      frame: 'simple',
      frameText: 'SCAN ME',
    },
  },
  {
    id: 'tpl-4',
    name: 'Neon Cyber Media',
    category: 'Creative',
    description: 'Vibrant cyan gradient with dot pattern for image, audio, and video media QRs.',
    previewColor: '#06b6d4',
    customization: {
      ...DEFAULT_CUSTOMIZATION,
      fgColor: '#0891b2',
      bgColor: '#f0fdf4',
      gradientEnabled: true,
      gradientColor: '#2563eb',
      pattern: 'dots',
      eyeStyle: 'dot',
      eyeColor: '#0284c7',
      frame: 'scanner',
      frameText: 'SCAN MEDIA',
    },
  },
];
